# Generated by Django 4.2.6 on 2023-10-25 09:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name for the category(e.g. sport)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular product', primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='Enter a label for the product', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter a price for the product', max_digits=10)),
                ('description', models.TextField(help_text='Enter a brief description of the product', max_length=1000)),
                ('image', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(help_text='select a category for the product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mercadona_app.category')),
            ],
        ),
    ]
