# Generated by Django 4.2.6 on 2023-10-25 11:33

from django.db import migrations, models
import django.db.models.deletion
import mercadona_app.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mercadona_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this promotion', primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('discount_percentage', models.PositiveIntegerField(help_text='Enter a percentage for the promotion. it must be positive and under 100', validators=[mercadona_app.models.validate_inferior_100])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercadona_app.product')),
            ],
        ),
    ]
