# Generated by Django 4.2.6 on 2023-10-25 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercadona_app', '0002_promotion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
    ]
