# Generated by Django 4.2.6 on 2023-10-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadona_app', '0003_rename_category_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
