# Generated by Django 4.2.6 on 2023-11-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercadona_app', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['label']},
        ),
    ]
