# Generated by Django 4.2.6 on 2023-11-10 13:01

from django.db import migrations, models
import mercadona_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadona_app', '0007_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[mercadona_app.models.validate_image_extension]),
        ),
    ]
